# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
         vmImage: ubuntu-18.04
        variables:
          dockerfileloc: '$(Build.SourcesDirectory)/Dockerfile'
          buildtag: '$(Build.BuildId)'
        steps:
          - task: Docker@2
            displayName: build and push image into acr
            inputs:
              containerRegistry: 'mydemoreg'
              repository: 'yoga'
              command: 'buildAndPush'
              Dockerfile: '$(dockerfileloc)'
              tags: '$(buildtag)'
            condition: succeeded()
      
      - job: publish
        pool:
          vmImage: ubuntu-18.04
        dependsOn: Build
        variables:
          frmdir: '$(Build.SourcesDirectory)'
          todir: '$(Build.ArtifactStagingDirectory)'
          contenttocopied: '*yml'
        steps:
          - task: CopyFiles@2
            displayName: copy from source directory to staging directory
            inputs:
              SourceFolder: '$(frmdir)'
              Contents: '$(contenttocopied)'
              TargetFolder: '$(todir)'
              OverWrite: true
              preserveTimestamp: true

          - task: PublishBuildArtifacts@1
            displayName: publish artifcat
            inputs:
              PathtoPublish: '$(todir)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
            condition: succeeded()